/*
 * Appointments Backend
 *
 * # API for appointment scheduling related data  This is the API of the service at P7M that manages the scheduling and management of appointments. It is used by the booking widget (see the **WidgetApi** tag) with functions that are public and don't require the user to be authenticated.  For endpoints in other tags the caller has to be authenticated with the system and provide a JWT token in the Authorization header of the HTTP request. When using the API you typically get this token by authenticating first with OAuth 2.0.  When you are trying this API using the Swagger interface, you need to click the `Authorize` button and then again the Authorize button in the pop-up that gets opened.
 *
 * The version of the OpenAPI document: 0.13.1
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListWrapperBookingTenantDataInner {
    #[serde(rename = "tenantId")]
    pub tenant_id: uuid::Uuid,
    #[serde(rename = "timezone")]
    pub timezone: String,
    #[serde(rename = "reservationLimitMode")]
    pub reservation_limit_mode: models::ReservationLimit,
    #[serde(rename = "reservationLimitDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reservation_limit_date: Option<Option<String>>,
    #[serde(rename = "reservationLimitDays", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reservation_limit_days: Option<Option<i32>>,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "phone")]
    pub phone: String,
    #[serde(rename = "fax")]
    pub fax: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "emailSignature")]
    pub email_signature: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "emailInternal")]
    pub email_internal: String,
    #[serde(rename = "calendarExtraInfo")]
    pub calendar_extra_info: String,
    #[serde(rename = "requiredConditions")]
    pub required_conditions: Vec<String>,
    #[serde(rename = "holidayRegionId")]
    pub holiday_region_id: uuid::Uuid,
}

impl ListWrapperBookingTenantDataInner {
    pub fn new(tenant_id: uuid::Uuid, timezone: String, reservation_limit_mode: models::ReservationLimit, address: String, phone: String, fax: String, email: String, email_signature: String, name: String, email_internal: String, calendar_extra_info: String, required_conditions: Vec<String>, holiday_region_id: uuid::Uuid) -> ListWrapperBookingTenantDataInner {
        ListWrapperBookingTenantDataInner {
            tenant_id,
            timezone,
            reservation_limit_mode,
            reservation_limit_date: None,
            reservation_limit_days: None,
            address,
            phone,
            fax,
            email,
            email_signature,
            name,
            email_internal,
            calendar_extra_info,
            required_conditions,
            holiday_region_id,
        }
    }
}

