/*
 * Appointments Backend
 *
 * # API for appointment scheduling related data  This is the API of the service at P7M that manages the scheduling and management of appointments. It is used by the booking widget (see the **WidgetApi** tag) with functions that are public and don't require the user to be authenticated.  For endpoints in other tags the caller has to be authenticated with the system and provide a JWT token in the Authorization header of the HTTP request. When using the API you typically get this token by authenticating first with OAuth 2.0.  When you are trying this API using the Swagger interface, you need to click the `Authorize` button and then again the Authorize button in the pop-up that gets opened.
 *
 * The version of the OpenAPI document: 0.13.1
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListWrapperAvailabilityDataInner {
    #[serde(rename = "availabilityId")]
    pub availability_id: uuid::Uuid,
    #[serde(rename = "tenantId")]
    pub tenant_id: uuid::Uuid,
    #[serde(rename = "workerId")]
    pub worker_id: uuid::Uuid,
    #[serde(rename = "dayOfWeek")]
    pub day_of_week: models::DayOfWeek,
    #[serde(rename = "startTime")]
    pub start_time: String,
    #[serde(rename = "endTime")]
    pub end_time: String,
    #[serde(rename = "services")]
    pub services: Vec<uuid::Uuid>,
    #[serde(rename = "notBefore", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub not_before: Option<Option<String>>,
    #[serde(rename = "notAfter", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub not_after: Option<Option<String>>,
}

impl ListWrapperAvailabilityDataInner {
    pub fn new(availability_id: uuid::Uuid, tenant_id: uuid::Uuid, worker_id: uuid::Uuid, day_of_week: models::DayOfWeek, start_time: String, end_time: String, services: Vec<uuid::Uuid>) -> ListWrapperAvailabilityDataInner {
        ListWrapperAvailabilityDataInner {
            availability_id,
            tenant_id,
            worker_id,
            day_of_week,
            start_time,
            end_time,
            services,
            not_before: None,
            not_after: None,
        }
    }
}

