/*
 * Appointments Backend
 *
 * # API for appointment scheduling related data  This is the API of the service at P7M that manages the scheduling and management of appointments. It is used by the booking widget (see the **WidgetApi** tag) with functions that are public and don't require the user to be authenticated.  For the endpoint in the other tags, the caller has to be authenticated with the system and provide a JWT token in the Authorization header of the HTTP request. If your interacting with this API using the Swagger interface, you need to set the JWT token by clicking on the **Authorize** button on the right side of the header. As the value don't forget that the Authorization header starts with the fixed value `Bearer` followed by a space followed by the actual JWT token value.  If anything is unclear or you found a bug in the documentation, please contact <tech@p7m.de>. 
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TenantConfig {
    #[serde(rename = "services")]
    pub services: Vec<crate::models::ServiceConfig>,
    #[serde(rename = "workers")]
    pub workers: Vec<crate::models::WorkerConfig>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "address")]
    pub address: Vec<String>,
    #[serde(rename = "phone")]
    pub phone: String,
    #[serde(rename = "phone_national")]
    pub phone_national: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "calendar_extra_info")]
    pub calendar_extra_info: String,
    #[serde(rename = "required_conditions")]
    pub required_conditions: Vec<String>,
}

impl TenantConfig {
    pub fn new(services: Vec<crate::models::ServiceConfig>, workers: Vec<crate::models::WorkerConfig>, name: String, address: Vec<String>, phone: String, phone_national: String, email: String, calendar_extra_info: String, required_conditions: Vec<String>) -> TenantConfig {
        TenantConfig {
            services,
            workers,
            name,
            address,
            phone,
            phone_national,
            email,
            calendar_extra_info,
            required_conditions,
        }
    }
}


